---
- name: install nginx
  hosts: 192.168.1.140
  task:
  - name: install nginx
    yum: install=nginx
  - name:  enable nginx
    service: name=nginx enabled=true
  - name: nginx status
    service: name=nginx state=status
